"""W1: OSINT secrets encrypted at rest (B14), auth modes, SQL-side global search and workspace counts (B15)."""

import os
import tempfile
from pathlib import Path

if "DATABASE_URL" not in os.environ:  # standalone run; under a full pytest run another module may have set it
    _tmp = Path(tempfile.mkdtemp())
    os.environ["DATABASE_URL"] = f"sqlite:///{(_tmp / 'test.db').as_posix()}"
os.environ["ANTHROPIC_API_KEY"] = ""

import pytest  # noqa: E402
from cryptography.fernet import Fernet  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402
from sqlalchemy import inspect, text  # noqa: E402

from app import osint, secrets  # noqa: E402
from app.config import get_settings  # noqa: E402
from app.db import Base, SessionLocal, engine  # noqa: E402
from app.main import app  # noqa: E402
from app.models import Research, Setting  # noqa: E402

LEAD = {"X-User": "skapoor"}
HUNTER = {"X-User": "averma"}


@pytest.fixture()
def c():
    with TestClient(app) as cl:
        yield cl


@pytest.fixture()
def secret_key(monkeypatch):
    monkeypatch.setattr(get_settings(), "threatlens_secret_key", Fernet.generate_key().decode())
    secrets.reset()
    yield
    secrets.reset()


@pytest.fixture()
def clean_keys():
    def wipe():
        with SessionLocal() as db:
            row = db.get(Setting, "osint_keys")
            if row:
                db.delete(row)
                db.commit()
    wipe()
    yield
    wipe()


# ------------------------------------------------------------------ B14 secrets

def test_encrypt_roundtrip_and_mask(secret_key):
    tok = secrets.encrypt("abcdef1234567890")
    assert tok.startswith("enc:v1:") and "abcdef" not in tok
    assert secrets.decrypt(tok) == "abcdef1234567890"
    assert secrets.decrypt("legacy-plain") == "legacy-plain"
    assert secrets.mask("abcdef1234567890") == "••••7890"
    assert secrets.mask("short") == "••••"  # too short to reveal any characters
    assert secrets.mask("") == ""


def test_non_fernet_env_key_is_stretched(monkeypatch):
    monkeypatch.setattr(get_settings(), "threatlens_secret_key", "correct horse battery staple")
    secrets.reset()
    try:
        assert secrets.decrypt(secrets.encrypt("x")) == "x"
    finally:
        secrets.reset()


def test_key_autogenerated_into_data_dir(monkeypatch, tmp_path, caplog):
    monkeypatch.setattr(get_settings(), "threatlens_secret_key", "")
    monkeypatch.delenv("THREATLENS_SECRET_KEY", raising=False)
    monkeypatch.setattr(get_settings(), "data_dir", tmp_path)
    secrets.reset()
    try:
        tok = secrets.encrypt("v")
        assert (tmp_path / ".secret_key").exists()
        assert "THREATLENS_SECRET_KEY is not set" in caplog.text
        secrets.reset()  # re-read from file: same key
        assert secrets.decrypt(tok) == "v"
    finally:
        secrets.reset()


def test_wrong_key_means_not_configured(secret_key, monkeypatch):
    tok = secrets.encrypt("k")
    monkeypatch.setattr(get_settings(), "threatlens_secret_key", Fernet.generate_key().decode())
    secrets.reset()
    assert secrets.decrypt(tok) == ""


def test_put_keys_encrypts_and_api_masks(c, secret_key, clean_keys):
    full = "vt-SECRET-abcdefghijkl-9876"
    assert c.put("/api/settings/osint-keys", json={"keys": {"virustotal": full}}, headers=HUNTER).status_code == 403
    r = c.put("/api/settings/osint-keys", json={"keys": {"virustotal": full, "bogus": "x"}}, headers=LEAD)
    assert r.status_code == 200
    assert full not in r.text and "SECRET" not in r.text
    vt = next(k for k in r.json() if k["id"] == "virustotal")
    assert vt["configured"] is True and vt["source"] == "settings" and vt["hint"] == "••••9876"
    got = c.get("/api/settings/osint-keys").json()
    assert full not in str(got)
    with SessionLocal() as db:
        stored = db.get(Setting, "osint_keys").value
        assert set(stored) == {"virustotal"} and stored["virustotal"].startswith("enc:v1:")
        # Readers (pipeline, library re-enrich) get the usable key through osint.get_keys.
        assert osint.get_keys(db)["virustotal"] == full
        assert secrets.get_secret("virustotal", db) == full
    r = c.put("/api/settings/osint-keys", json={"keys": {"virustotal": None}}, headers=LEAD)
    assert next(k for k in r.json() if k["id"] == "virustotal")["source"] != "settings"


def test_legacy_plaintext_migrated_on_read_and_startup(c, secret_key, clean_keys):
    with SessionLocal() as db:
        db.merge(Setting(key="osint_keys", value={"shodan": "plain-shodan-key-5555"}))
        db.commit()
    c.get("/api/settings/osint-keys")
    with SessionLocal() as db:
        assert db.get(Setting, "osint_keys").value["shodan"].startswith("enc:v1:")
        db.merge(Setting(key="osint_keys", value={"otx": "plain-otx-key-4444"}))
        db.commit()
    Base.metadata.create_all(engine)  # startup path: migrate.upgrade runs after create_all
    with SessionLocal() as db:
        v = db.get(Setting, "osint_keys").value["otx"]
        assert v.startswith("enc:v1:") and secrets.decrypt(v) == "plain-otx-key-4444"


# ------------------------------------------------------------------ schema upkeep

def test_create_all_restores_missing_index_and_column():
    with engine.begin() as conn:
        conn.execute(text("DROP INDEX IF EXISTS ix_research_severity"))
    Base.metadata.create_all(engine)
    names = {i["name"] for i in inspect(engine).get_indexes("research")}
    assert {"ix_research_severity", "ix_research_status", "ix_research_created_at"} <= names
    assert "ix_activity_event_research_created" in {i["name"] for i in inspect(engine).get_indexes("activity_event")}


# ------------------------------------------------------------------ auth modes

def test_dev_mode_keeps_user_switcher(c):
    assert c.get("/api/me", headers=HUNTER).json()["id"] == "averma"
    assert c.get("/api/me", headers={"X-User": "nobody"}).status_code == 200  # falls back to the first user


def test_header_mode(c, monkeypatch):
    s = get_settings()
    monkeypatch.setattr(s, "auth_mode", "header")
    monkeypatch.setattr(s, "auth_trusted_proxies", "testclient,10.0.0.0/8")
    h = {"X-Forwarded-Email": "S.Kapoor@threatlens.local"}
    assert c.get("/api/me", headers=h).json()["id"] == "skapoor"
    # X-User is ignored in header mode
    assert c.get("/api/me", headers={**h, "X-User": "averma"}).json()["id"] == "skapoor"
    assert c.get("/api/me", headers=HUNTER).status_code == 401
    assert c.get("/api/me", headers={"X-Forwarded-Email": "stranger@example.com"}).status_code == 403
    monkeypatch.setattr(s, "auth_header", "X-Auth-Request-Email")
    assert c.get("/api/me", headers={"X-Auth-Request-Email": "a.verma@threatlens.local"}).json()["id"] == "averma"
    monkeypatch.setattr(s, "auth_trusted_proxies", "10.0.0.0/8")  # TestClient's peer is not a trusted proxy
    assert c.get("/api/me", headers={"X-Auth-Request-Email": "a.verma@threatlens.local"}).status_code == 401


def test_oidc_mode_is_501(c, monkeypatch):
    monkeypatch.setattr(get_settings(), "auth_mode", "oidc")
    r = c.get("/api/me")
    assert r.status_code == 501 and "OIDC_ISSUER" in r.json()["detail"]


def test_trusted_proxy_matching():
    from app.deps import _trusted
    assert _trusted("127.0.0.1", "127.0.0.1,::1")
    assert _trusted("10.1.2.3", "10.0.0.0/8")
    assert not _trusted("192.168.1.1", "10.0.0.0/8")
    assert not _trusted(None, "127.0.0.1")
    assert not _trusted("evil", "127.0.0.1")


# ------------------------------------------------------------------ search and workspaces

def test_search_sql_ranks_exact_id_first(c):
    with SessionLocal() as db:
        rid = db.query(Research.id).filter(Research.status != "archived").first()[0]
    r = c.get("/api/search", params={"q": rid.lower()}).json()
    grp = next(g for g in r["groups"] if g["label"] == "Research")
    assert grp["items"][0]["id"] == rid
    # LIKE wildcards in user text are literal, not match-everything
    r = c.get("/api/search", params={"q": "%"}).json()
    assert all(g["label"] != "Research" for g in r["groups"])
    r = c.get("/api/search", params={"q": "toolshell"}).json()
    assert any(g["label"] == "Research" and g["items"] for g in r["groups"])
    assert len(next(g for g in r["groups"] if g["label"] == "Research")["items"]) <= 6


def test_workspace_counts_match_python(c):
    with SessionLocal() as db:
        rows = db.query(Research.workspace_ids).all()
    expect = {}
    for (ids,) in rows:
        for w in set(ids or []):
            expect[w] = expect.get(w, 0) + 1
    for w in c.get("/api/workspaces").json():
        assert w["research_count"] == expect.get(w["id"], 0)


def test_research_fts_tracks_inserts_updates_deletes(c):
    from app.migrate import research_fts_available
    with SessionLocal() as db:
        if not research_fts_available(db):
            pytest.skip("SQLite without FTS5 trigram")
        db.add(Research(id="TR-2098-0001", title="W1 fts probe", status="draft", search_text="w1 quokkaprobe marker"))
        db.commit()
    hit = lambda q: [i["id"] for g in c.get("/api/search", params={"q": q}).json()["groups"] if g["label"] == "Research" for i in g["items"]]  # noqa: E731
    try:
        assert hit("quokkaprobe") == ["TR-2098-0001"]
        assert hit("QUOKKA") == ["TR-2098-0001"]  # case-insensitive substring
        assert hit("tr-2098-0001") == ["TR-2098-0001"]  # id is indexed too
        with SessionLocal() as db:
            db.get(Research, "TR-2098-0001").search_text = "w1 wombatprobe marker"
            db.commit()
        assert hit("quokkaprobe") == [] and hit("wombatprobe") == ["TR-2098-0001"]
    finally:
        with SessionLocal() as db:
            db.delete(db.get(Research, "TR-2098-0001"))
            db.commit()
    assert hit("wombatprobe") == []
